version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
     - .:/app
    environment:
     - "APP_SETTINGS=config.Develop"
    ports:
     - "127.0.0.1:5000:5000"
    #command: bash -c "flask run"
  redis:
    image: "redis:alpine"
    expose:
     - "6379"
    command: ["redis-server", "--loglevel", "warning"]
