"""empty message

Revision ID: bea8b596da9f
Revises: d1542e3762c1
Create Date: 2019-04-14 17:49:24.231680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea8b596da9f'
down_revision = 'd1542e3762c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'latitude',
                    existing_type=sa.NUMERIC(precision=8, scale=0),
                    type_=sa.Numeric(precision=9, scale=7, asdecimal=False),
                    existing_nullable=True)
    op.alter_column('locations', 'longitude',
                    existing_type=sa.NUMERIC(precision=8, scale=0),
                    type_=sa.Numeric(precision=9, scale=7, asdecimal=False),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'longitude',
                    existing_type=sa.Numeric(precision=9, scale=7, asdecimal=False),
                    type_=sa.NUMERIC(precision=8, scale=0),
                    existing_nullable=True)
    op.alter_column('locations', 'latitude',
                    existing_type=sa.Numeric(precision=9, scale=7, asdecimal=False),
                    type_=sa.NUMERIC(precision=8, scale=0),
                    existing_nullable=True)
    # ### end Alembic commands ###
